spring:
  application:
    name: Droply
  datasource:
    url: "jdbc:postgresql://localhost/droply"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 16
      auto-commit: false
      connection-timeout: 10000
      idle-timeout: 60000
      minimum-idle: 2
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:changelog.yml

droply:
  security:
    issuer: "Droply"
    keys:
      public: "keys/public.pem"
      private: "keys/private.pem"
  ktor:
    host: "0.0.0.0"
    port: 8081
  auth:
    google:
      clientId: "560884241902-p1atlsdr1i1sc79icipgbled726ek470.apps.googleusercontent.com"